[package]
name = "roma-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
roma-core = { path = "../roma-core" }
roma-engine = { path = "../roma-engine" }
ratatui.workspace = true
crossterm.workspace = true
tui-tree-widget.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
